version: "3.8"
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python telegram/telegram.py
